using System;
using System.Collections.Generic;
using System.Globalization;
using ReactiveUI;

namespace MapRegionizer.App.Services;

public sealed class LocalizationService : ReactiveObject
{
    private readonly Dictionary<string, Dictionary<string, string>> _resources = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en-US"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AppTitle"] = "MapRegionizer",
            ["SettingsTitle"] = "Generation settings",
            ["InputOutput"] = "Input and output",
            ["Mask"] = "Map mask",
            ["Output"] = "Output folder",
            ["Browse"] = "Browse",
            ["Choose"] = "Choose",
            ["Language"] = "Language",
            ["Theme"] = "Theme",
            ["Light"] = "Light",
            ["Dark"] = "Dark",
            ["System"] = "System",
            ["Preset"] = "Preset",
            ["Profile"] = "Profile",
            ["BasicSettings"] = "Basic settings",
            ["AdvancedSettings"] = "Advanced settings",
            ["Navigation"] = "Navigation",
            ["ProjectGroup"] = "Project",
            ["MapGroup"] = "Map",
            ["AdvancedGroup"] = "Advanced",
            ["GenerationSection"] = "Generation",
            ["QualityProfile"] = "Quality profile",
            ["Relief"] = "Relief",
            ["WaterRivers"] = "Water and rivers",
            ["Biomes"] = "Biomes",
            ["LayerProperties"] = "Layer properties",
            ["GenerationLog"] = "Generation log",
            ["Thumbnails"] = "Thumbnails",
            ["NoGenerationLog"] = "No generation log yet",
            ["LayerUnavailable"] = "not ready",
            ["LogGenerationStarted"] = "Generation started",
            ["LogStageStarted"] = "Stage started",
            ["LogStageCompleted"] = "Stage completed",
            ["LogGenerationCompleted"] = "Generation completed",
            ["LogGenerationCancelled"] = "Generation cancelled",
            ["LogRegionsStarted"] = "Region generation started",
            ["LogRegionsCompleted"] = "Region generation completed",
            ["RegionSize"] = "Region size",
            ["HelpRegionSize"] = "Target average region area. Higher values produce fewer, larger regions.",
            ["HelpPointsMultiplier"] = "Controls how many candidate points are sampled before region filtering.",
            ["HelpMinAreaRatio"] = "Minimum allowed region area relative to the target size.",
            ["HelpMaxAreaRatio"] = "Maximum allowed region area relative to the target size.",
            ["HelpDistortionEnabled"] = "Adds more natural curved boundaries after raw region generation.",
            ["HelpBoundaryDetail"] = "Controls boundary curve density. Higher values add more detail.",
            ["FastPreview"] = "Fast preview",
            ["Balanced"] = "Balanced",
            ["Detailed"] = "Detailed",
            ["DiagnosticExport"] = "Diagnostics",
            ["DiagnosticExportFull"] = "Diagnostic export",
            ["General"] = "General",
            ["Regions"] = "Regions",
            ["Boundaries"] = "Boundaries",
            ["Tectonics"] = "Tectonics",
            ["Elevation"] = "Elevation",
            ["Seed"] = "Seed",
            ["Randomize"] = "Randomize",
            ["Copy"] = "Copy",
            ["Projection"] = "Projection",
            ["PixelSize"] = "Pixel size",
            ["SimplifyTolerance"] = "Simplify tolerance",
            ["TargetArea"] = "Target region area",
            ["PointsMultiplier"] = "Points multiplier",
            ["MinAreaRatio"] = "Min area ratio",
            ["MaxAreaRatio"] = "Max area ratio",
            ["DistortionEnabled"] = "Distort boundaries",
            ["BoundaryDetail"] = "Boundary detail",
            ["MaxOffset"] = "Max offset",
            ["MinLineLengthToCurve"] = "Min line length to curve",
            ["PlateCount"] = "Plate count",
            ["HotspotCount"] = "Hotspot count",
            ["ContinentalSeedRatio"] = "Continental seed ratio",
            ["BoundaryNoise"] = "Boundary noise",
            ["BoundaryNoiseScale"] = "Boundary noise scale",
            ["LandWaterTransitionPenalty"] = "Land/water transition penalty",
            ["Activity"] = "Activity",
            ["EarthLikeFactor"] = "Earth-like factor",
            ["HistoryDepth"] = "History depth",
            ["MicroplateRatio"] = "Microplate ratio",
            ["MicroplateAreaRatio"] = "Microplate area ratio min/max",
            ["MinBoundarySegmentLength"] = "Min boundary segment length",
            ["ActiveMarginRatio"] = "Active margin ratio",
            ["ShelfWidthFactor"] = "Shelf width factor",
            ["RiftChance"] = "Rift chance",
            ["ValidateGeometry"] = "Validate geometry",
            ["ValidationCycles"] = "Validation cycles",
            ["MinPlateSize"] = "Min plate size",
            ["MinPlateSizeRatio"] = "Min plate size ratio",
            ["ReliefScale"] = "Relief scale",
            ["Mountaininess"] = "Mountaininess",
            ["Erosion"] = "Erosion",
            ["Roughness"] = "Roughness",
            ["SeaDepthScale"] = "Sea depth scale",
            ["PreserveCoastline"] = "Preserve mask coastline",
            ["VolcanismInfluence"] = "Volcanism influence",
            ["SmallIslandReliefFactor"] = "Small island relief",
            ["GenerateSmallLakes"] = "Generate small lakes",
            ["SmallLakeCountMultiplier"] = "Small lake count multiplier",
            ["SmallLakeScatterMultiplier"] = "Small lake scatter multiplier",
            ["SmallLakeSizeMultiplier"] = "Small lake size multiplier",
            ["RiftInfluence"] = "Rift influence",
            ["MaxElevation"] = "Max elevation, m",
            ["MinOceanDepth"] = "Min ocean depth, m",
            ["MinLandElevation"] = "Min land elevation, m",
            ["MaxSeaElevation"] = "Max sea elevation, m",
            ["TectonicJson"] = "Tectonic JSON",
            ["ElevationJson"] = "Elevation JSON",
            ["ClimateJson"] = "Climate JSON",
            ["ExportSettings"] = "Export",
            ["ExportScale"] = "PNG scale",
            ["ExportRegionBorderWidth"] = "Region border width",
            ["ExportTectonicBoundaryWidth"] = "Tectonic boundary width",
            ["ExportCrustPlateBoundaries"] = "Plate boundaries on crust",
            ["ExportFeaturePlateBoundaries"] = "Plate boundaries on features",
            ["ExportElevationHillshade"] = "Elevation hillshade",
            ["ExportElevationPlateBoundaries"] = "Plate boundaries on elevation",
            ["ExportClimateHillshade"] = "Climate hillshade",
            ["ExportClimateRivers"] = "Rivers on climate",
            ["ExportClimateRiverValleys"] = "River-valley accents",
            ["HelpExportScale"] = "Multiplies PNG output dimensions. GeoJSON and JSON exports are unchanged.",
            ["RiverDensity"] = "River density",
            ["MajorRiverCountMultiplier"] = "Major river count multiplier",
            ["LongRiverCountMultiplier"] = "Long river count multiplier",
            ["TributaryDensity"] = "Tributary density",
            ["MajorRiverTributaryMultiplier"] = "Major-river tributary multiplier",
            ["LakeOutletInflowForceMultiplier"] = "Lake outlet inflow force",
            ["EndorheicBasinChance"] = "Endorheic basin chance",
            ["MaxEndorheicBasins"] = "Max endorheic basins",
            ["DeltaFrequency"] = "Delta frequency",
            ["MeanderStrength"] = "Meander strength",
            ["LakeOutletStrictness"] = "Lake outlet strictness",
            ["PreserveRiverCoastline"] = "Preserve river coastline",
            ["AllowRiverCarving"] = "Allow river carving",
            ["OceanSeaMinAreaRatio"] = "Ocean/sea min area ratio",
            ["InlandSeaMinAreaRatio"] = "Inland sea min area ratio",
            ["OceanSeaNearOceanDistance"] = "Near-ocean distance, cells",
            ["PreserveOceanCoastline"] = "Preserve ocean coastline",
            ["PreserveInlandWaterMask"] = "Preserve inland water mask",
            ["LakeSurfacePercentile"] = "Lake surface percentile",
            ["ClimatePolarLatitudeMargin"] = "Polar latitude margin",
            ["ClimateEquatorTemperature"] = "Equator temperature, C",
            ["ClimatePoleCooling"] = "Pole cooling, C",
            ["ClimateLapseRate"] = "Lapse rate, C/m",
            ["ClimateOrographicStrength"] = "Orographic strength",
            ["ClimateRiverMoistureBonus"] = "River moisture bonus",
            ["ClimateRiverAgricultureBonus"] = "River agriculture bonus",
            ["ClimateSnowMeltThreshold"] = "Snow melt threshold, C",
            ["ClimateSnowPrecipitationScale"] = "Snow precipitation scale",
            ["MountainRiverDensity"] = "Mountain river density",
            ["MaxMountainSourcesPerCluster"] = "Max mountain sources per cluster",
            ["MinMountainSourceSpacing"] = "Min mountain source spacing",
            ["MinMicroplateAreaRatio"] = "Min microplate area ratio",
            ["MaxMicroplateAreaRatio"] = "Max microplate area ratio",
            ["ElevationShelfWidthFactor"] = "Shelf width (elevation)",
            ["AllowLakeExpansion"] = "Allow lake expansion",
            ["AllowLakeDrainage"] = "Allow lake drainage",
            ["MinLakeSurfaceMarginMeters"] = "Min lake surface margin, m",
            ["MaxLakeSurfaceMarginMeters"] = "Max lake surface margin, m",
            ["MinLakeDepthMeters"] = "Min lake depth, m",
            ["MaxLakeDepthMeters"] = "Max lake depth, m",
            ["MaxRiftLakeDepthMeters"] = "Max rift lake depth, m",
            ["MaxInlandSeaDepthMeters"] = "Max inland sea depth, m",
            ["MountainLakeElevationMeters"] = "Mountain lake elevation, m",
            ["PlateauLakeElevationMeters"] = "Plateau lake elevation, m",
            ["MountainLakeReliefMeters"] = "Mountain lake relief, m",
            ["LakeTectonicFaultThreshold"] = "Lake tectonic fault threshold",
            ["LakeVolcanicInfluenceThreshold"] = "Lake volcanic influence threshold",
            ["PlainLakeKarstChance"] = "Plain lake karst chance",
            ["LakeDepthRandomnessMin"] = "Lake depth randomness min",
            ["LakeDepthRandomnessMax"] = "Lake depth randomness max",
            ["LargeLakeDepressionMinCellCount"] = "Large lake depression, cells",
            ["ClimateLatitudeCurveExponent"] = "Latitude curve exponent",
            ["ClimateBaseSeasonalityCelsius"] = "Base seasonality, C",
            ["ClimateLatitudeSeasonalityCelsius"] = "Latitude seasonality, C",
            ["ClimateContinentalSeasonalityCelsius"] = "Continental seasonality, C",
            ["ClimateContinentalSummerBoostCelsius"] = "Continental summer boost, C",
            ["ClimateContinentalWinterPenaltyCelsius"] = "Continental winter penalty, C",
            ["ClimateContinentalityDistanceCells"] = "Continentality distance, cells",
            ["ClimateLargeLakeMinCellCount"] = "Large lake min cell count",
            ["ClimateOceanEvaporation"] = "Ocean evaporation",
            ["ClimateLakeEvaporation"] = "Lake evaporation",
            ["ClimateLandEvapotranspiration"] = "Land evapotranspiration",
            ["ClimateMoistureRetention"] = "Moisture retention",
            ["ClimateBaseRainfallEfficiency"] = "Base rainfall efficiency",
            ["ClimateDescentDrying"] = "Descent drying",
            ["ClimateContinentalDrying"] = "Continental drying",
            ["ClimateMonsoonRainStrength"] = "Monsoon rain strength",
            ["ClimateDrySeasonStrength"] = "Dry season strength",
            ["ClimateMonsoonOceanDistanceCells"] = "Monsoon ocean distance, cells",
            ["ClimateMonsoonCoastProbeCells"] = "Monsoon coast probe, cells",
            ["LayerReady"] = "ready",
            ["Size"] = "Size",
            ["Landmasses"] = "Landmasses",
            ["WaterBodies"] = "Water bodies",
            ["GeneratedLakes"] = "Generated lakes",
            ["WaterSurfaces"] = "Water surfaces",
            ["Plates"] = "Plates",
            ["Features"] = "Features",
            ["RunFull"] = "Generate",
            ["RunRegionsOnly"] = "Generate regions only",
            ["RegionsOnly"] = "Regions only",
            ["Export"] = "Export",
            ["ExportPreview"] = "Export Preview",
            ["Cancel"] = "Cancel",
            ["Preview"] = "Preview",
            ["Compare"] = "Compare",
            ["Fit"] = "Fit",
            ["Zoom"] = "Zoom",
            ["Position"] = "Position",
            ["Layers"] = "Layers",
            ["Stages"] = "Stages",
            ["Statistics"] = "Statistics",
            ["History"] = "History",
            ["Artifacts"] = "Artifacts",
            ["Diagnostics"] = "Diagnostics",
            ["SelectedMask"] = "Selected mask",
            ["Ready"] = "Ready",
            ["Generating"] = "Generating...",
            ["GeneratingRegions"] = "Generating regions...",
            ["Completed"] = "Generation completed",
            ["RegionsCompleted"] = "Regions generated",
            ["Failed"] = "Generation failed",
            ["NotStarted"] = "Not started",
            ["Running"] = "Running",
            ["StageReady"] = "Ready",
            ["Dirty"] = "Dirty",
            ["StageFailed"] = "Failed",
            ["Unavailable"] = "Unavailable",
            ["RunUntil"] = "Run",
            ["Regenerate"] = "Refresh",
            ["More"] = "More",
            ["Less"] = "Less",
            ["MoreValue"] = "More",
            ["Smooth"] = "Smooth",
            ["DetailedScale"] = "Detailed",
            ["RunUntilHint"] = "Run generation up to this stage.",
            ["RefreshStageHint"] = "Regenerate this stage and mark dependent results dirty.",
            ["CopySeedHint"] = "Copy the current seed.",
            ["ShowArtifacts"] = "Show artifacts",
            ["Load"] = "Load",
            ["OpenFolder"] = "Open folder",
            ["Continue"] = "Continue",
            ["Stop"] = "Stop",
            ["FutureStages"] = "Future stages",
            ["Rivers"] = "Rivers",
            ["Climate"] = "Climate",
            ["Resources"] = "Resources",
            ["NoPreview"] = "No preview yet",
            ["NoHistory"] = "No runs yet",
            ["OnboardingTitle"] = "Quick start",
            ["OnboardingStepMask"] = "1. Choose a map mask.",
            ["OnboardingStepPreset"] = "2. Pick a generation preset.",
            ["OnboardingStepGenerate"] = "3. Click Generate.",
            ["OnboardingStepExport"] = "4. Review layers and export the result.",
            ["DismissOnboarding"] = "Hide quick start",
            ["ValidationMask"] = "Choose an existing mask image.",
            ["ValidationOutput"] = "Choose an output folder.",
            ["ValidationOptions"] = "Fix invalid generation settings.",
            ["StatusChooseMask"] = "Choose a mask to begin.",
            ["StatusSessionReset"] = "Session will be recreated on the next run.",
            ["StatusDirty"] = "Settings changed. Affected stages are dirty.",
            ["StatusExported"] = "Artifacts exported.",
            ["StatusGenerateFirst"] = "Generate the map first.",
            ["StatusPreviewExported"] = "Preview exported.",
            ["LayerOverview"] = "Overview",
            ["LayerRegions"] = "Regions",
            ["LayerTectonicPlates"] = "Tectonic plates",
            ["LayerCrust"] = "Crust",
            ["LayerFeatures"] = "Tectonic features",
            ["LayerElevation"] = "Elevation",
            ["LayerElevationBase"] = "Elevation base",
            ["LayerElevationTectonic"] = "Tectonic elevation",
            ["LayerElevationRoughness"] = "Roughness",
            ["LayerElevationErosion"] = "Erosion mask",
            ["LayerElevationZones"] = "Terrain zones",
            ["LayerElevationMountain"] = "Mountain influence",
            ["LayerElevationBasin"] = "Basin influence",
            ["LayerElevationRivers"] = "Rivers",
            ["LayerClimateBiomesDebug"] = "Climate biomes debug",
            ["LayerClimateBiomesPresentation"] = "Climate biomes presentation",
            ["LayerClimateTemperature"] = "Temperature",
            ["LayerClimateMoisture"] = "Moisture",
            ["LayerClimatePrecipitation"] = "Precipitation",
            ["LayerClimateSeasonality"] = "Seasonality",
            ["LayerClimateHabitability"] = "Habitability",
            ["LayerClimateAgriculture"] = "Agriculture",
            ["LayerClimateIce"] = "Ice",
            ["LegendOverview"] = "Land, water, and generated region borders.",
            ["LegendTectonics"] = "Plate ids, plate boundaries, and tectonic diagnostics.",
            ["LegendElevation"] = "Hypsometric terrain and bathymetry.",
            ["LegendClimate"] = "Climate biomes, temperature, moisture, rainfall, habitability, agriculture, and ice.",
            ["LegendNotAvailable"] = "Run the required stage to render this layer."
            ,
            ["StageLandmasses"] = "Extract landmasses",
            ["StageWaterBodies"] = "Extract water bodies",
            ["StageWaterBodyTopology"] = "Classify water bodies",
            ["StageTectonicHistory"] = "Tectonic history",
            ["StageCrustFields"] = "Crust fields",
            ["StagePlateDomains"] = "Plate domains",
            ["StageTectonicBoundaries"] = "Plate boundaries",
            ["StageOrogenProvinces"] = "Orogen provinces",
            ["StageRiftProvinces"] = "Rift provinces",
            ["StageTectonicFeatures"] = "Tectonic features",
            ["StageElevation"] = "Elevation",
            ["StageBaseTerrain"] = "Base terrain",
            ["StageGeneratedLakes"] = "Generated lakes",
            ["StageLakeLevels"] = "Lake levels",
            ["StageHydrology"] = "Hydrology",
            ["StageClimate"] = "Climate",
            ["StageTectonicPlates"] = "Tectonic map",
            ["StageRawRegions"] = "Raw regions",
            ["StageRegions"] = "Final regions",
            ["StageLandmassesDescription"] = "Extracts land polygons from the source mask.",
            ["StageWaterBodiesDescription"] = "Builds water bodies from the land mask.",
            ["StageWaterBodyTopologyDescription"] = "Classifies oceans, seas, inland lakes, and inland seas.",
            ["StageTectonicHistoryDescription"] = "Creates the synthetic tectonic scenario.",
            ["StageCrustFieldsDescription"] = "Classifies crust, shelves, ages, and coastal zones.",
            ["StagePlateDomainsDescription"] = "Assigns map cells to tectonic plate domains.",
            ["StageTectonicBoundariesDescription"] = "Classifies local plate boundaries and motion.",
            ["StageOrogenProvincesDescription"] = "Builds mountain-building provinces from convergent tectonics.",
            ["StageRiftProvincesDescription"] = "Builds rift provinces from extensional tectonics.",
            ["StageTectonicFeaturesDescription"] = "Derives uplift, volcanism, seismicity, and features.",
            ["StageElevationDescription"] = "Generates final elevation and diagnostic terrain fields.",
            ["StageBaseTerrainDescription"] = "Generates pre-hydrology terrain and bathymetry.",
            ["StageGeneratedLakesDescription"] = "Selects small terrain-derived lake footprints.",
            ["StageLakeLevelsDescription"] = "Applies lake surfaces and writes final elevation.",
            ["StageHydrologyDescription"] = "Routes runoff, lakes, river basins, and visible rivers.",
            ["StageClimateDescription"] = "Generates temperature, moisture, biomes, habitability, agriculture, monsoon, rain-shadow, and ice rasters.",
            ["StageTectonicPlatesDescription"] = "Assembles the compatibility tectonic plate map.",
            ["StageRawRegionsDescription"] = "Creates raw region polygons before boundary distortion.",
            ["StageRegionsDescription"] = "Builds final regions after post-processing.",
            ["HelpSeed"] = "Random seed for deterministic generation. Same seed with the same mask produces identical maps.",
            ["HelpProjection"] = "Map projection mode: EquirectangularWorld (full globe), Flat (no lat/lon distortion), or Regional (local area).",
            ["HelpPixelSize"] = "Pixel size in map units. Affects resolution of generated raster data.",
            ["HelpSimplifyTolerance"] = "Douglas-Peucker simplification tolerance for mask polygon extraction. Higher values produce simpler shapes.",
            ["HelpOceanSeaMinAreaRatio"] = "Minimum area ratio to classify a water body as ocean/sea. Higher values require larger connected areas.",
            ["HelpInlandSeaMinAreaRatio"] = "Minimum area ratio to classify a water body as inland sea. Must be <= Ocean sea min area ratio.",
            ["HelpOceanSeaNearOceanDistance"] = "Maximum distance in cells from ocean for near-ocean classification. Higher = more seas classed as oceanic.",
            ["HelpPreserveOceanCoastline"] = "Preserve the original mask coastline for oceans during elevation generation.",
            ["HelpPreserveInlandWaterMask"] = "Preserve the original inland water bodies from the mask during generation.",
            ["HelpReliefScale"] = "Overall scale multiplier for terrain elevation. Higher values produce more dramatic relief.",
            ["HelpMountaininess"] = "How mountainous the terrain is. 0 = flat plains, 1 = very mountainous.",
            ["HelpRoughness"] = "Terrain roughness / micro-relief intensity. Higher values create more jagged, irregular terrain.",
            ["HelpSeaDepthScale"] = "Overall depth multiplier for ocean bathymetry. Higher values produce deeper oceans.",
            ["HelpMaxElevation"] = "Maximum allowed land elevation in meters. Caps the highest mountain peaks.",
            ["HelpMinOceanDepth"] = "Minimum (deepest) ocean depth in meters. Negative values below sea level.",
            ["HelpPreserveCoastline"] = "Preserve the original mask coastline as a hard constraint during elevation generation.",
            ["HelpRiverDensity"] = "Overall density of river networks. Higher values produce more rivers with denser branching.",
            ["HelpMajorRiverCountMultiplier"] = "Multiplier for the number of major rivers. Higher = more large river systems.",
            ["HelpTributaryDensity"] = "Density of tributary streams feeding into rivers. Higher values produce more complex drainage.",
            ["HelpMeanderStrength"] = "How strongly rivers meander. 0 = straight channels, 1 = highly sinuous rivers.",
            ["HelpGenerateSmallLakes"] = "Enable generation of small procedural lakes in terrain depressions outside major water bodies.",
            ["HelpPreserveRiverCoastline"] = "Preserve coastlines when routing rivers to the ocean. Prevents rivers from carving through coasts.",
            ["HelpAllowRiverCarving"] = "Allow rivers to carve into terrain, creating valleys and gorges over time.",
            ["HelpClimatePolarLatitudeMargin"] = "Margin from the poles where polar climate begins. 0 = pole-only, 0.99 = nearly entire map.",
            ["HelpClimateEquatorTemperature"] = "Baseline temperature at the equator in degrees Celsius.",
            ["HelpClimatePoleCooling"] = "Temperature drop from equator to poles in C. Higher = colder poles.",
            ["HelpClimateLapseRate"] = "Temperature decrease per meter of elevation gain in C/m. Higher = colder mountains.",
            ["HelpClimateOrographicStrength"] = "How strongly mountain barriers enhance rainfall on windward slopes. Higher = stronger rain shadows.",
            ["HelpClimateRiverMoistureBonus"] = "Additional moisture near rivers, supporting riparian and wet biomes.",
            ["HelpClimateRiverAgricultureBonus"] = "Agricultural fertility bonus near rivers due to irrigation and alluvial soil.",
            ["HelpClimateSnowMeltThreshold"] = "Temperature threshold in C above which snow melts. Higher = snow persists at warmer temperatures.",
            ["HelpClimateSnowPrecipitationScale"] = "Scale factor for snowfall amount relative to total precipitation.",
            ["HelpExportRegionBorderWidth"] = "Width of region boundary lines in exported images.",
            ["HelpExportTectonicBoundaryWidth"] = "Width of tectonic plate boundary lines in exported images.",
            ["HelpExportElevationHillshade"] = "Draw hillshade overlay on elevation export images.",
            ["HelpExportClimateHillshade"] = "Draw hillshade overlay on climate export images.",
            ["HelpExportClimateRivers"] = "Draw river lines on climate biome export images.",
            ["HelpPlateCount"] = "Number of tectonic plates to generate. Null = auto-determine from map size.",
            ["HelpHotspotCount"] = "Number of mantle hotspots. Hotspots create volcanic chains and continental rifts.",
            ["HelpContinentalSeedRatio"] = "Ratio of continental vs oceanic plate seeds. Higher = more continental plates.",
            ["HelpBoundaryNoise"] = "Noise applied to plate boundary shapes. Higher = more irregular, natural-looking boundaries.",
            ["HelpActivity"] = "Overall tectonic activity level. 0 = quiet, 1 = normal, 2 = highly active with more boundaries.",
            ["HelpEarthLikeFactor"] = "How Earth-like the tectonic configuration is. 0 = alien, 1 = mimics Earth plate patterns.",
            ["HelpHistoryDepth"] = "How far back the tectonic simulation goes. 0 = minimal history, 1 = deep geological history.",
            ["HelpValidateGeometry"] = "Validate plate geometry for topological correctness. Fixes overlaps and gaps.",
            ["HelpErosion"] = "Overall erosion strength. 0 = no erosion, 1 = maximum flattening of terrain.",
            ["HelpSmallLakeCountMultiplier"] = "Multiplier for the number of generated small lakes. Higher = more lakes.",
            ["HelpSmallLakeScatterMultiplier"] = "Controls how widely small lakes are scattered across the terrain.",
            ["HelpSmallLakeSizeMultiplier"] = "Size multiplier for generated small lakes. Higher = larger lakes.",
            ["HelpLakeSurfacePercentile"] = "Percentile of elevation distribution used to set lake surface levels. Higher = deeper lakes on average.",
            ["HelpEndorheicBasinChance"] = "Probability that a basin has no ocean outlet. Higher = more inland drainage basins.",
            ["HelpMaxEndorheicBasins"] = "Maximum number of endorheic (closed) basins that can form.",
            ["HelpTectonicJson"] = "Export detail for tectonic plates JSON. Summary = key data; Full = all diagnostics.",
            ["HelpElevationJson"] = "Export detail for elevation JSON. Summary = key data; Full = all diagnostic fields.",
            ["HelpClimateJson"] = "Export detail for climate JSON. Summary = key data; Full = all climate rasters.",
            ["HelpMaxOffset"] = "Maximum offset distance for boundary distortion points. Higher = more dramatic curves.",
            ["HelpMinLineLengthToCurve"] = "Minimum line segment length before boundary distortion curves are applied.",
            ["HelpBoundaryNoiseScale"] = "Scale of noise used to perturb plate boundaries. Higher = larger wavelength wiggles.",
            ["HelpLandWaterTransitionPenalty"] = "Penalty applied to plate boundaries crossing land-water edges.",
            ["HelpMicroplateRatio"] = "Target ratio of microplates to total plate count.",
            ["HelpLongRiverCountMultiplier"] = "Multiplier for the number of long rivers spanning large distances.",
            ["HelpMajorRiverTributaryMultiplier"] = "Multiplier for tributaries of major rivers.",
            ["HelpLakeOutletInflowForceMultiplier"] = "How strongly inflow forces lake outlets. Higher = more outlets.",
            ["HelpDeltaFrequency"] = "Frequency of river deltas at coastlines.",
            ["HelpLakeOutletStrictness"] = "How strictly lake outlets follow lowest point. Higher = more precise drainage.",
            ["HelpMinBoundarySegmentLength"] = "Minimum length of individual boundary segments in cells.",
            ["HelpActiveMarginRatio"] = "Ratio of active (convergent/divergent) margins. Higher = more tectonic activity.",
            ["HelpShelfWidthFactor"] = "Width multiplier for continental shelves. Higher = wider shelves.",
            ["HelpRiftChance"] = "Probability of rift formation at boundaries. Higher = more rifting.",
            ["HelpValidationCycles"] = "Geometry validation cycles. Higher = more thorough topological correction.",
            ["HelpMinPlateSize"] = "Minimum allowed size of a tectonic plate in cells.",
            ["HelpMinPlateSizeRatio"] = "Minimum size ratio of a tectonic plate relative to total map area.",
            ["HelpVolcanismInfluence"] = "How strongly volcanism affects elevation. Higher = more volcanic terrain uplift.",
            ["HelpSmallIslandReliefFactor"] = "Relief scale factor for small islands. Lower = flatter islands.",
            ["HelpRiftInfluence"] = "How strongly rifting affects elevation. Higher = more rift valley terrain.",
            ["HelpMinLandElevation"] = "Minimum allowed elevation for land cells in meters.",
            ["HelpMaxSeaElevation"] = "Maximum allowed elevation for sea cells in meters (negative = below sea level).",
            ["HelpMountainRiverDensity"] = "Density of river sources originating in mountainous terrain.",
            ["HelpMaxMountainSourcesPerCluster"] = "Maximum number of river sources per mountain cluster.",
            ["HelpMinMountainSourceSpacing"] = "Minimum distance between mountain river sources in cells.",
            ["HelpMinMicroplateAreaRatio"] = "Minimum area ratio for individual microplates.",
            ["HelpMaxMicroplateAreaRatio"] = "Maximum area ratio for individual microplates.",
            ["HelpElevationShelfWidthFactor"] = "Width factor for continental shelf during elevation generation.",
            ["HelpAllowLakeExpansion"] = "Allow lakes to expand beyond their initial depressions.",
            ["HelpAllowLakeDrainage"] = "Allow lakes to drain and form through-flowing systems.",
            ["HelpMinLakeSurfaceMarginMeters"] = "Minimum vertical margin between lake surface and surrounding terrain, m.",
            ["HelpMaxLakeSurfaceMarginMeters"] = "Maximum vertical margin between lake surface and surrounding terrain, m.",
            ["HelpMinLakeDepthMeters"] = "Minimum depth for generated lakes in meters.",
            ["HelpMaxLakeDepthMeters"] = "Maximum depth for generated lakes in meters.",
            ["HelpMaxRiftLakeDepthMeters"] = "Maximum depth for rift valley lakes in meters.",
            ["HelpMaxInlandSeaDepthMeters"] = "Maximum depth for inland sea water bodies in meters.",
            ["HelpMountainLakeElevationMeters"] = "Elevation threshold for mountain lake classification in meters.",
            ["HelpPlateauLakeElevationMeters"] = "Elevation threshold for plateau lake classification in meters.",
            ["HelpMountainLakeReliefMeters"] = "Minimum local relief for mountain lake classification in meters.",
            ["HelpLakeTectonicFaultThreshold"] = "Threshold of tectonic fault influence for lake formation.",
            ["HelpLakeVolcanicInfluenceThreshold"] = "Threshold of volcanic influence for lake formation.",
            ["HelpPlainLakeKarstChance"] = "Probability of karst-related lake formation in plains.",
            ["HelpLakeDepthRandomnessMin"] = "Minimum randomness multiplier for lake depth variation.",
            ["HelpLakeDepthRandomnessMax"] = "Maximum randomness multiplier for lake depth variation.",
            ["HelpLargeLakeDepressionMinCellCount"] = "Minimum cell count for a depression to be a large lake basin.",
            ["HelpClimateLatitudeCurveExponent"] = "Controls how temperature drops with latitude. Higher = steeper polar cooling.",
            ["HelpClimateBaseSeasonalityCelsius"] = "Baseline seasonal temperature variation in C.",
            ["HelpClimateLatitudeSeasonalityCelsius"] = "Additional seasonality at high latitudes in C.",
            ["HelpClimateContinentalSeasonalityCelsius"] = "Seasonality increase in continental interiors in C.",
            ["HelpClimateContinentalSummerBoostCelsius"] = "Summer temperature boost for continental interiors in C.",
            ["HelpClimateContinentalWinterPenaltyCelsius"] = "Winter temperature penalty for continental interiors in C.",
            ["HelpClimateContinentalityDistanceCells"] = "Distance from coast for continentality effects in cells.",
            ["HelpClimateLargeLakeMinCellCount"] = "Minimum cell count for a lake to moderate local climate.",
            ["HelpClimateOceanEvaporation"] = "Evaporation rate from ocean surfaces. Higher = more rainfall.",
            ["HelpClimateLakeEvaporation"] = "Evaporation rate from lake surfaces relative to oceans.",
            ["HelpClimateLandEvapotranspiration"] = "Evapotranspiration rate from land. Higher = more recycled moisture.",
            ["HelpClimateMoistureRetention"] = "Atmospheric moisture retention. Higher = more humid climate.",
            ["HelpClimateBaseRainfallEfficiency"] = "Base efficiency converting moisture into rainfall.",
            ["HelpClimateDescentDrying"] = "How strongly descending air dries the landscape.",
            ["HelpClimateContinentalDrying"] = "Moisture loss as air moves inland. Higher = drier interiors.",
            ["HelpClimateMonsoonRainStrength"] = "Strength of monsoon rainfall enhancement.",
            ["HelpClimateDrySeasonStrength"] = "Strength of the dry season in monsoon regions.",
            ["HelpClimateMonsoonOceanDistanceCells"] = "Distance monsoon influence extends inland from ocean, cells.",
            ["HelpClimateMonsoonCoastProbeCells"] = "Cells probed for coastline direction in monsoon calculation."
        },
        ["ru-RU"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AppTitle"] = "MapRegionizer",
            ["SettingsTitle"] = "Настройки генерации",
            ["InputOutput"] = "Ввод и вывод",
            ["Mask"] = "Маска карты",
            ["Output"] = "Папка вывода",
            ["Browse"] = "Обзор",
            ["Choose"] = "Выбрать",
            ["Language"] = "Язык",
            ["Theme"] = "Тема",
            ["Light"] = "Светлая",
            ["Dark"] = "Темная",
            ["System"] = "Системная",
            ["Preset"] = "Пресет",
            ["Profile"] = "Профиль",
            ["BasicSettings"] = "Основные параметры",
            ["AdvancedSettings"] = "Расширенные параметры",
            ["Navigation"] = "Навигация",
            ["ProjectGroup"] = "Проект",
            ["MapGroup"] = "Карта",
            ["AdvancedGroup"] = "Дополнительно",
            ["GenerationSection"] = "Генерация",
            ["QualityProfile"] = "Профиль качества",
            ["Relief"] = "Рельеф",
            ["WaterRivers"] = "Вода и реки",
            ["Biomes"] = "Биомы",
            ["LayerProperties"] = "Свойства слоя",
            ["GenerationLog"] = "Лог генерации",
            ["Thumbnails"] = "Миниатюры",
            ["NoGenerationLog"] = "Лога генерации пока нет",
            ["LayerUnavailable"] = "не готово",
            ["LogGenerationStarted"] = "Генерация запущена",
            ["LogStageStarted"] = "Стадия начата",
            ["LogStageCompleted"] = "Стадия завершена",
            ["LogGenerationCompleted"] = "Генерация завершена",
            ["LogGenerationCancelled"] = "Генерация отменена",
            ["LogRegionsStarted"] = "Генерация регионов запущена",
            ["LogRegionsCompleted"] = "Генерация регионов завершена",
            ["RegionSize"] = "Размер регионов",
            ["HelpRegionSize"] = "Средняя целевая площадь региона. Больше значение - меньше и крупнее регионы.",
            ["HelpPointsMultiplier"] = "Сколько точек-кандидатов генерируется перед фильтрацией регионов.",
            ["HelpMinAreaRatio"] = "Минимальная площадь региона относительно целевого размера.",
            ["HelpMaxAreaRatio"] = "Максимальная площадь региона относительно целевого размера.",
            ["HelpDistortionEnabled"] = "Добавляет более естественные изогнутые границы после генерации регионов.",
            ["HelpBoundaryDetail"] = "Плотность изгибов границ. Чем выше значение, тем больше деталей.",
            ["FastPreview"] = "Быстрый просмотр",
            ["Balanced"] = "Баланс",
            ["Detailed"] = "Детальный",
            ["DiagnosticExport"] = "Диагностика",
            ["DiagnosticExportFull"] = "Диагностический экспорт",
            ["General"] = "Общие",
            ["Regions"] = "Регионы",
            ["Boundaries"] = "Границы",
            ["Tectonics"] = "Тектоника",
            ["Elevation"] = "Рельеф",
            ["Seed"] = "Seed",
            ["Randomize"] = "Случайный",
            ["Copy"] = "Копировать",
            ["Projection"] = "Проекция",
            ["PixelSize"] = "Масштаб пикселя",
            ["SimplifyTolerance"] = "Упрощение маски",
            ["TargetArea"] = "Целевая площадь региона",
            ["PointsMultiplier"] = "Множитель точек",
            ["MinAreaRatio"] = "Мин. отношение площади",
            ["MaxAreaRatio"] = "Макс. отношение площади",
            ["DistortionEnabled"] = "Искажать границы",
            ["BoundaryDetail"] = "Детализация границ",
            ["MaxOffset"] = "Макс. отступ",
            ["MinLineLengthToCurve"] = "Мин. длина для изгиба",
            ["PlateCount"] = "Количество плит",
            ["HotspotCount"] = "Количество хотспотов",
            ["ContinentalSeedRatio"] = "Доля континентальных сидов",
            ["BoundaryNoise"] = "Шум границ",
            ["BoundaryNoiseScale"] = "Масштаб шума границ",
            ["LandWaterTransitionPenalty"] = "Штраф перехода суша/вода",
            ["Activity"] = "Активность",
            ["EarthLikeFactor"] = "Землеподобность",
            ["HistoryDepth"] = "Глубина истории",
            ["MicroplateRatio"] = "Доля микроплит",
            ["MicroplateAreaRatio"] = "Мин/макс. доля площади микроплит",
            ["MinBoundarySegmentLength"] = "Мин. длина сегмента границы",
            ["ActiveMarginRatio"] = "Доля активных окраин",
            ["ShelfWidthFactor"] = "Множитель ширины шельфа",
            ["RiftChance"] = "Вероятность рифта",
            ["ValidateGeometry"] = "Проверять геометрию",
            ["ValidationCycles"] = "Циклы проверки",
            ["MinPlateSize"] = "Мин. размер плиты",
            ["MinPlateSizeRatio"] = "Мин. доля размера плиты",
            ["ReliefScale"] = "Масштаб рельефа",
            ["Mountaininess"] = "Гористость",
            ["Erosion"] = "Эрозия",
            ["Roughness"] = "Шероховатость",
            ["SeaDepthScale"] = "Глубина морей",
            ["PreserveCoastline"] = "Сохранять береговую линию маски",
            ["VolcanismInfluence"] = "Влияние вулканизма",
            ["SmallIslandReliefFactor"] = "Рельеф малых островов",
            ["GenerateSmallLakes"] = "Генерировать малые озера",
            ["SmallLakeCountMultiplier"] = "Множитель числа малых озер",
            ["SmallLakeScatterMultiplier"] = "Разброс малых озер",
            ["SmallLakeSizeMultiplier"] = "Множитель размера малых озер",
            ["RiftInfluence"] = "Влияние рифтов",
            ["MaxElevation"] = "Макс. высота, м",
            ["MinOceanDepth"] = "Мин. глубина океана, м",
            ["MinLandElevation"] = "Мин. высота суши, м",
            ["MaxSeaElevation"] = "Макс. высота моря, м",
            ["TectonicJson"] = "JSON тектоники",
            ["ElevationJson"] = "JSON рельефа",
            ["ClimateJson"] = "JSON климата",
            ["ExportSettings"] = "Экспорт",
            ["ExportScale"] = "Масштаб PNG",
            ["ExportRegionBorderWidth"] = "Толщина границ регионов",
            ["ExportTectonicBoundaryWidth"] = "Толщина тектонических границ",
            ["ExportCrustPlateBoundaries"] = "Границы плит на коре",
            ["ExportFeaturePlateBoundaries"] = "Границы плит на признаках",
            ["ExportElevationHillshade"] = "Тени рельефа",
            ["ExportElevationPlateBoundaries"] = "Границы плит на рельефе",
            ["ExportClimateHillshade"] = "Тени климата",
            ["ExportClimateRivers"] = "Реки на климате",
            ["ExportClimateRiverValleys"] = "Акценты речных долин",
            ["HelpExportScale"] = "Умножает размер PNG. GeoJSON и JSON экспортируются без изменений.",
            ["RiverDensity"] = "Плотность рек",
            ["MajorRiverCountMultiplier"] = "Множитель крупных рек",
            ["LongRiverCountMultiplier"] = "Множитель длинных рек",
            ["TributaryDensity"] = "Плотность притоков",
            ["MajorRiverTributaryMultiplier"] = "Притоки крупных рек",
            ["LakeOutletInflowForceMultiplier"] = "Приток к выходам озер",
            ["EndorheicBasinChance"] = "Шанс бессточного бассейна",
            ["MaxEndorheicBasins"] = "Макс. бессточных рек",
            ["DeltaFrequency"] = "Частота дельт",
            ["MeanderStrength"] = "Сила меандрирования",
            ["LakeOutletStrictness"] = "Строгость выходов озер",
            ["PreserveRiverCoastline"] = "Сохранять берег для рек",
            ["AllowRiverCarving"] = "Разрешить врезание рек",
            ["OceanSeaMinAreaRatio"] = "Мин. доля океана/моря",
            ["InlandSeaMinAreaRatio"] = "Мин. доля внутреннего моря",
            ["OceanSeaNearOceanDistance"] = "Дистанция до океана, ячейки",
            ["PreserveOceanCoastline"] = "Сохранять океанский берег",
            ["PreserveInlandWaterMask"] = "Сохранять внутренние воды",
            ["LakeSurfacePercentile"] = "Перцентиль уровня озер",
            ["ClimatePolarLatitudeMargin"] = "Полярная широтная граница",
            ["ClimateEquatorTemperature"] = "Температура экватора, C",
            ["ClimatePoleCooling"] = "Охлаждение полюсов, C",
            ["ClimateLapseRate"] = "Высотный градиент, C/м",
            ["ClimateOrographicStrength"] = "Сила орографических осадков",
            ["ClimateRiverMoistureBonus"] = "Бонус влажности от рек",
            ["ClimateRiverAgricultureBonus"] = "Бонус земледелия от рек",
            ["ClimateSnowMeltThreshold"] = "Порог таяния снега, C",
            ["ClimateSnowPrecipitationScale"] = "Масштаб снежных осадков",
            ["MountainRiverDensity"] = "Густота горных рек",
            ["MaxMountainSourcesPerCluster"] = "Макс. горных истоков на кластер",
            ["MinMountainSourceSpacing"] = "Мин. расстояние между горн. истоками",
            ["MinMicroplateAreaRatio"] = "Мин. доля площади микроплиты",
            ["MaxMicroplateAreaRatio"] = "Макс. доля площади микроплиты",
            ["ElevationShelfWidthFactor"] = "Ширина шельфа (рельеф)",
            ["AllowLakeExpansion"] = "Разрешить расширение озёр",
            ["AllowLakeDrainage"] = "Разрешить дренаж озёр",
            ["MinLakeSurfaceMarginMeters"] = "Мин. запас уровня озера, м",
            ["MaxLakeSurfaceMarginMeters"] = "Макс. запас уровня озера, м",
            ["MinLakeDepthMeters"] = "Мин. глубина озера, м",
            ["MaxLakeDepthMeters"] = "Макс. глубина озера, м",
            ["MaxRiftLakeDepthMeters"] = "Макс. глубина рифтовых озёр, м",
            ["MaxInlandSeaDepthMeters"] = "Макс. глубина внутр. морей, м",
            ["MountainLakeElevationMeters"] = "Высота горных озёр, м",
            ["PlateauLakeElevationMeters"] = "Высота плато-озёр, м",
            ["MountainLakeReliefMeters"] = "Рельеф горных озёр, м",
            ["LakeTectonicFaultThreshold"] = "Порог тектон. разломов для озёр",
            ["LakeVolcanicInfluenceThreshold"] = "Порог вулканизма для озёр",
            ["PlainLakeKarstChance"] = "Шанс карстовых озёр на равнине",
            ["LakeDepthRandomnessMin"] = "Мин. случайность глубины озёр",
            ["LakeDepthRandomnessMax"] = "Макс. случайность глубины озёр",
            ["LargeLakeDepressionMinCellCount"] = "Мин. ячеек депрессии озера",
            ["ClimateLatitudeCurveExponent"] = "Экспонента широтной кривой",
            ["ClimateBaseSeasonalityCelsius"] = "Базовая сезонность, C",
            ["ClimateLatitudeSeasonalityCelsius"] = "Широтная сезонность, C",
            ["ClimateContinentalSeasonalityCelsius"] = "Континент. сезонность, C",
            ["ClimateContinentalSummerBoostCelsius"] = "Континент. летнее усиление, C",
            ["ClimateContinentalWinterPenaltyCelsius"] = "Континент. зимний штраф, C",
            ["ClimateContinentalityDistanceCells"] = "Дистанция континент., ячейки",
            ["ClimateLargeLakeMinCellCount"] = "Мин. ячеек крупного озера",
            ["ClimateOceanEvaporation"] = "Испарение с океана",
            ["ClimateLakeEvaporation"] = "Испарение с озёр",
            ["ClimateLandEvapotranspiration"] = "Эвапотранспирация суши",
            ["ClimateMoistureRetention"] = "Удержание влаги",
            ["ClimateBaseRainfallEfficiency"] = "Базовая эффективность осадков",
            ["ClimateDescentDrying"] = "Сушка нисходящим воздухом",
            ["ClimateContinentalDrying"] = "Континентальное иссушение",
            ["ClimateMonsoonRainStrength"] = "Сила муссонных дождей",
            ["ClimateDrySeasonStrength"] = "Сила сухого сезона",
            ["ClimateMonsoonOceanDistanceCells"] = "Дист. муссона от океана, ячейки",
            ["ClimateMonsoonCoastProbeCells"] = "Зондирование берега муссона, яч.",
            ["LayerReady"] = "готово",
            ["Size"] = "Размер",
            ["Landmasses"] = "Массивы суши",
            ["WaterBodies"] = "Водоемы",
            ["Plates"] = "Плиты",
            ["Features"] = "Признаки",
            ["RunFull"] = "Генерировать",
            ["RunRegionsOnly"] = "Сгенерировать только регионы",
            ["RegionsOnly"] = "Только регионы",
            ["Export"] = "Экспорт",
            ["ExportPreview"] = "Экспорт изображения",
            ["Cancel"] = "Отмена",
            ["Preview"] = "Просмотр",
            ["Compare"] = "Сравнение",
            ["Fit"] = "Вписать",
            ["Zoom"] = "Масштаб",
            ["Position"] = "Позиция",
            ["Layers"] = "Слои",
            ["Stages"] = "Стадии",
            ["Statistics"] = "Статистика",
            ["History"] = "История",
            ["Artifacts"] = "Артефакты",
            ["Diagnostics"] = "Диагностика",
            ["SelectedMask"] = "Выбранная маска",
            ["Ready"] = "Готово",
            ["Generating"] = "Генерация...",
            ["GeneratingRegions"] = "Генерация регионов...",
            ["Completed"] = "Генерация завершена",
            ["RegionsCompleted"] = "Регионы сгенерированы",
            ["Failed"] = "Ошибка генерации",
            ["NotStarted"] = "Не запускалась",
            ["Running"] = "Выполняется",
            ["StageReady"] = "Готова",
            ["Dirty"] = "Устарела",
            ["StageFailed"] = "Ошибка",
            ["Unavailable"] = "Недоступно",
            ["RunUntil"] = "До",
            ["Regenerate"] = "Обновить",
            ["More"] = "Еще",
            ["Less"] = "Меньше",
            ["MoreValue"] = "Больше",
            ["Smooth"] = "Гладкие",
            ["DetailedScale"] = "Детальные",
            ["RunUntilHint"] = "Выполнить генерацию до этой стадии.",
            ["RefreshStageHint"] = "Перегенерировать эту стадию и пометить зависимые результаты устаревшими.",
            ["CopySeedHint"] = "Скопировать текущий seed.",
            ["ShowArtifacts"] = "Показать артефакты",
            ["Load"] = "Загрузить",
            ["OpenFolder"] = "Открыть папку",
            ["Continue"] = "Продолжить",
            ["Stop"] = "Остановить",
            ["FutureStages"] = "Будущие стадии",
            ["Rivers"] = "Реки",
            ["Climate"] = "Климат",
            ["Resources"] = "Ресурсы",
            ["NoPreview"] = "Превью пока нет",
            ["NoHistory"] = "Запусков пока нет",
            ["OnboardingTitle"] = "Быстрый старт",
            ["OnboardingStepMask"] = "1. Выберите маску карты.",
            ["OnboardingStepPreset"] = "2. Настройте пресет.",
            ["OnboardingStepGenerate"] = "3. Нажмите «Генерировать».",
            ["OnboardingStepExport"] = "4. Просмотрите слои и экспортируйте результат.",
            ["DismissOnboarding"] = "Скрыть быстрый старт",
            ["ValidationMask"] = "Выберите существующий файл маски.",
            ["ValidationOutput"] = "Выберите папку вывода.",
            ["ValidationOptions"] = "Исправьте некорректные настройки генерации.",
            ["StatusChooseMask"] = "Выберите маску, чтобы начать.",
            ["StatusSessionReset"] = "Сессия будет пересоздана при следующем запуске.",
            ["StatusDirty"] = "Настройки изменены. Зависимые стадии устарели.",
            ["StatusExported"] = "Артефакты экспортированы.",
            ["StatusGenerateFirst"] = "Сначала сгенерируйте карту.",
            ["StatusPreviewExported"] = "Изображение сохранено.",
            ["LayerOverview"] = "Обзор",
            ["LayerRegions"] = "Регионы",
            ["LayerTectonicPlates"] = "Тектонические плиты",
            ["LayerCrust"] = "Кора",
            ["LayerFeatures"] = "Тектонические features",
            ["LayerElevation"] = "Рельеф",
            ["LayerElevationBase"] = "База рельефа",
            ["LayerElevationTectonic"] = "Тектонический вклад",
            ["LayerElevationRoughness"] = "Шероховатость",
            ["LayerElevationErosion"] = "Маска эрозии",
            ["LayerElevationZones"] = "Зоны рельефа",
            ["LayerElevationMountain"] = "Влияние гор",
            ["LayerElevationBasin"] = "Влияние бассейнов",
            ["LayerElevationRivers"] = "Реки",
            ["LayerClimateBiomesDebug"] = "Климатические биомы debug",
            ["LayerClimateBiomesPresentation"] = "Климатические биомы presentation",
            ["LayerClimateTemperature"] = "Температура",
            ["LayerClimateMoisture"] = "Влажность",
            ["LayerClimatePrecipitation"] = "Осадки",
            ["LayerClimateSeasonality"] = "Сезонность",
            ["LayerClimateHabitability"] = "Обитаемость",
            ["LayerClimateAgriculture"] = "Земледелие",
            ["LayerClimateIce"] = "Лед",
            ["LegendOverview"] = "Суша, вода и границы сгенерированных регионов.",
            ["LegendTectonics"] = "Идентификаторы плит, границы плит и тектоническая диагностика.",
            ["LegendElevation"] = "Гипсометрический рельеф и батиметрия.",
            ["LegendClimate"] = "Биомы, температура, влажность, осадки, обитаемость, земледелие и лед.",
            ["LegendNotAvailable"] = "Запустите нужную стадию, чтобы отрисовать этот слой."
            ,
            ["StageLandmasses"] = "Извлечение суши",
            ["StageWaterBodies"] = "Извлечение водоемов",
            ["StageTectonicHistory"] = "Тектоническая история",
            ["StageCrustFields"] = "Поля коры",
            ["StagePlateDomains"] = "Домены плит",
            ["StageTectonicBoundaries"] = "Границы плит",
            ["StageTectonicFeatures"] = "Тектонические признаки",
            ["StageElevation"] = "Рельеф",
            ["StageHydrology"] = "Гидрология",
            ["StageClimate"] = "Климат",
            ["StageTectonicPlates"] = "Карта плит",
            ["StageRawRegions"] = "Черновые регионы",
            ["StageRegions"] = "Финальные регионы",
            ["StageLandmassesDescription"] = "Извлекает полигоны суши из исходной маски.",
            ["StageWaterBodiesDescription"] = "Строит водоемы на основе маски суши.",
            ["StageTectonicHistoryDescription"] = "Создает синтетический тектонический сценарий.",
            ["StageCrustFieldsDescription"] = "Классифицирует кору, шельфы, возраста и береговые зоны.",
            ["StagePlateDomainsDescription"] = "Назначает ячейки карты доменам тектонических плит.",
            ["StageTectonicBoundariesDescription"] = "Классифицирует локальные границы плит и движение.",
            ["StageTectonicFeaturesDescription"] = "Выводит uplift, вулканизм, сейсмичность и признаки.",
            ["StageElevationDescription"] = "Генерирует итоговый рельеф и диагностические поля.",
            ["StageHydrologyDescription"] = "Строит сток, озерные выходы, речные бассейны и видимые реки.",
            ["StageClimateDescription"] = "Генерирует температуру, влажность, биомы, обитаемость, земледелие, муссоны, дождевую тень и лед.",
            ["StageTectonicPlatesDescription"] = "Собирает совместимую карту тектонических плит.",
            ["StageRawRegionsDescription"] = "Создает черновые регионы до искажения границ.",
            ["StageRegionsDescription"] = "Строит финальные регионы после постобработки.",
            ["HelpSeed"] = "Случайное зерно для детерминированной генерации. То же зерно с той же маской даёт одинаковые карты.",
            ["HelpProjection"] = "Режим проекции: EquirectangularWorld (весь мир), Flat (плоская), Regional (локальная область).",
            ["HelpPixelSize"] = "Размер пикселя в единицах карты. Влияет на разрешение растровых данных.",
            ["HelpSimplifyTolerance"] = "Допуск упрощения полигонов маски по Дугласу-Пекеру. Выше = более простые формы.",
            ["HelpOceanSeaMinAreaRatio"] = "Мин. доля площади для классификации водоёма как океан/море. Выше = требуется большая связная площадь.",
            ["HelpInlandSeaMinAreaRatio"] = "Мин. доля площади для классификации внутреннего моря. Должно быть <= мин. доли океана/моря.",
            ["HelpOceanSeaNearOceanDistance"] = "Макс. дистанция от океана в ячейках для прибрежной классификации. Выше = больше морей считается океаническими.",
            ["HelpPreserveOceanCoastline"] = "Сохранять исходную береговую линию маски для океанов при генерации рельефа.",
            ["HelpPreserveInlandWaterMask"] = "Сохранять исходные внутренние водоёмы из маски при генерации.",
            ["HelpReliefScale"] = "Общий множитель высоты рельефа. Выше = более драматичный рельеф.",
            ["HelpMountaininess"] = "Гористость местности. 0 = равнины, 1 = очень гористо.",
            ["HelpRoughness"] = "Шероховатость/микрорельеф. Выше = более неровный, изрезанный рельеф.",
            ["HelpSeaDepthScale"] = "Множитель глубины океана. Выше = более глубокие океаны.",
            ["HelpMaxElevation"] = "Максимальная высота суши в метрах. Ограничивает высочайшие горные пики.",
            ["HelpMinOceanDepth"] = "Минимальная (самая глубокая) глубина океана в метрах. Отрицательные значения ниже ур. моря.",
            ["HelpPreserveCoastline"] = "Сохранять исходную береговую линию маски как жёсткое ограничение при генерации рельефа.",
            ["HelpRiverDensity"] = "Общая плотность речной сети. Выше = больше рек и гуще разветвление.",
            ["HelpMajorRiverCountMultiplier"] = "Множитель количества крупных рек. Выше = больше крупных речных систем.",
            ["HelpTributaryDensity"] = "Плотность притоков. Выше = более сложный дренаж.",
            ["HelpMeanderStrength"] = "Сила меандрирования рек. 0 = прямые русла, 1 = сильно извилистые реки.",
            ["HelpGenerateSmallLakes"] = "Генерировать небольшие процедурные озёра в понижениях рельефа вне основных водоёмов.",
            ["HelpPreserveRiverCoastline"] = "Сохранять береговую линию при прокладке рек к океану.",
            ["HelpAllowRiverCarving"] = "Позволить рекам врезаться в рельеф, создавая долины и ущелья.",
            ["HelpClimatePolarLatitudeMargin"] = "Отступ от полюсов, где начинается полярный климат. 0 = только полюса, 0.99 = почти вся карта.",
            ["HelpClimateEquatorTemperature"] = "Базовая температура на экваторе в градусах Цельсия.",
            ["HelpClimatePoleCooling"] = "Падение температуры от экватора к полюсам в C. Выше = холоднее полюса.",
            ["HelpClimateLapseRate"] = "Падение температуры на метр высоты в C/м. Выше = холоднее в горах.",
            ["HelpClimateOrographicStrength"] = "Как сильно горные барьеры усиливают осадки. Выше = сильнее дождевая тень.",
            ["HelpClimateRiverMoistureBonus"] = "Дополнительная влажность вблизи рек, поддерживающая приречные биомы.",
            ["HelpClimateRiverAgricultureBonus"] = "Бонус плодородия почв вблизи рек благодаря орошению и аллювию.",
            ["HelpClimateSnowMeltThreshold"] = "Температурный порог таяния снега в C. Выше = снег сохраняется при более тёплой погоде.",
            ["HelpClimateSnowPrecipitationScale"] = "Множитель количества снега относительно общих осадков.",
            ["HelpExportRegionBorderWidth"] = "Толщина линий границ регионов на экспортируемых изображениях.",
            ["HelpExportTectonicBoundaryWidth"] = "Толщина линий границ тектонических плит на экспортируемых изображениях.",
            ["HelpExportElevationHillshade"] = "Рисовать тени рельефа на экспортных изображениях высот.",
            ["HelpExportClimateHillshade"] = "Рисовать тени рельефа на экспортных изображениях климата.",
            ["HelpExportClimateRivers"] = "Рисовать линии рек на экспортных изображениях климатических биомов.",
            ["HelpPlateCount"] = "Количество тектонических плит. Null = авто-определение по размеру карты.",
            ["HelpHotspotCount"] = "Количество мантийных хотспотов. Хотспоты создают вулканические цепи и рифты.",
            ["HelpContinentalSeedRatio"] = "Доля континентальных затравок плит. Выше = больше континентальных плит.",
            ["HelpBoundaryNoise"] = "Шум формы границ плит. Выше = более неровные, естественные границы.",
            ["HelpActivity"] = "Уровень тектонической активности. 0 = спокойно, 1 = нормально, 2 = высокая активность.",
            ["HelpEarthLikeFactor"] = "Насколько тектоника похожа на земную. 0 = чужеродно, 1 = имитация Земли.",
            ["HelpHistoryDepth"] = "Глубина тектонической симуляции. 0 = минимум, 1 = глубокая геологическая история.",
            ["HelpValidateGeometry"] = "Проверять геометрию плит на топологическую корректность. Исправляет наложения и зазоры.",
            ["HelpErosion"] = "Общая сила эрозии. 0 = нет эрозии, 1 = макс. сглаживание рельефа.",
            ["HelpSmallLakeCountMultiplier"] = "Множитель количества малых озёр. Выше = больше озёр.",
            ["HelpSmallLakeScatterMultiplier"] = "Контроль разброса малых озёр по территории.",
            ["HelpSmallLakeSizeMultiplier"] = "Множитель размера малых озёр. Выше = крупнее озёра.",
            ["HelpLakeSurfacePercentile"] = "Перцентиль высот для уровня озёр. Выше = более глубокие озёра в среднем.",
            ["HelpEndorheicBasinChance"] = "Вероятность бессточного бассейна. Выше = больше внутреннего стока.",
            ["HelpMaxEndorheicBasins"] = "Максимальное количество бессточных (замкнутых) бассейнов.",
            ["HelpTectonicJson"] = "Детальность JSON тектоники. Summary = основные данные, Full = вся диагностика.",
            ["HelpElevationJson"] = "Детальность JSON рельефа. Summary = основные данные, Full = все диагностические поля.",
            ["HelpClimateJson"] = "Детальность JSON климата. Summary = основные данные, Full = все климатические растры.",
            ["HelpMaxOffset"] = "Макс. смещение точек искажения границ. Выше = более драматичные изгибы.",
            ["HelpMinLineLengthToCurve"] = "Мин. длина сегмента перед применением искажения границ.",
            ["HelpBoundaryNoiseScale"] = "Масштаб шума для возмущения границ плит. Выше = волнистость крупнее.",
            ["HelpLandWaterTransitionPenalty"] = "Штраф для границ плит, пересекающих границу суши и воды.",
            ["HelpMicroplateRatio"] = "Целевая доля микроплит от общего числа плит.",
            ["HelpLongRiverCountMultiplier"] = "Множитель количества длинных рек, пересекающих большие расстояния.",
            ["HelpMajorRiverTributaryMultiplier"] = "Множитель притоков крупных рек.",
            ["HelpLakeOutletInflowForceMultiplier"] = "Как сильно приток влияет на выходы озёр. Выше = больше выходов.",
            ["HelpDeltaFrequency"] = "Частота речных дельт на побережьях.",
            ["HelpLakeOutletStrictness"] = "Строгость следования выходов озёр нижней точке. Выше = точнее дренаж.",
            ["HelpMinBoundarySegmentLength"] = "Мин. длина отдельных сегментов границ в ячейках.",
            ["HelpActiveMarginRatio"] = "Доля активных (конвергентных/дивергентных) границ.",
            ["HelpShelfWidthFactor"] = "Множитель ширины континентального шельфа.",
            ["HelpRiftChance"] = "Вероятность образования рифта на границе плит.",
            ["HelpValidationCycles"] = "Циклы проверки геометрии. Выше = тщательнее коррекция.",
            ["HelpMinPlateSize"] = "Мин. размер тектонической плиты в ячейках.",
            ["HelpMinPlateSizeRatio"] = "Мин. доля размера плиты относительно всей карты.",
            ["HelpVolcanismInfluence"] = "Как сильно вулканизм влияет на рельеф. Выше = больше вулкан. форм.",
            ["HelpSmallIslandReliefFactor"] = "Множитель рельефа малых островов. Ниже = более плоские острова.",
            ["HelpRiftInfluence"] = "Как сильно рифтинг влияет на рельеф. Выше = больше рифтовых долин.",
            ["HelpMinLandElevation"] = "Мин. высота суши в метрах.",
            ["HelpMaxSeaElevation"] = "Макс. высота моря в метрах (отрицательные = ниже ур. моря).",
            ["HelpMountainRiverDensity"] = "Густота истоков рек в горной местности.",
            ["HelpMaxMountainSourcesPerCluster"] = "Макс. количество речных истоков на горный кластер.",
            ["HelpMinMountainSourceSpacing"] = "Мин. расстояние между горными истоками рек в ячейках.",
            ["HelpMinMicroplateAreaRatio"] = "Мин. доля площади для отдельной микроплиты.",
            ["HelpMaxMicroplateAreaRatio"] = "Макс. доля площади для отдельной микроплиты.",
            ["HelpElevationShelfWidthFactor"] = "Множитель ширины шельфа при генерации рельефа.",
            ["HelpAllowLakeExpansion"] = "Разрешить озёрам расширяться за пределы начальных понижений.",
            ["HelpAllowLakeDrainage"] = "Разрешить озёрам дренироваться и образовывать проточные системы.",
            ["HelpMinLakeSurfaceMarginMeters"] = "Мин. запас между поверхностью озера и окружением, м.",
            ["HelpMaxLakeSurfaceMarginMeters"] = "Макс. запас между поверхностью озера и окружением, м.",
            ["HelpMinLakeDepthMeters"] = "Мин. глубина генерируемых озёр в метрах.",
            ["HelpMaxLakeDepthMeters"] = "Макс. глубина генерируемых озёр в метрах.",
            ["HelpMaxRiftLakeDepthMeters"] = "Макс. глубина рифтовых озёр в метрах.",
            ["HelpMaxInlandSeaDepthMeters"] = "Макс. глубина внутренних морей в метрах.",
            ["HelpMountainLakeElevationMeters"] = "Порог высоты для классификации горного озера в метрах.",
            ["HelpPlateauLakeElevationMeters"] = "Порог высоты для классификации плато-озера в метрах.",
            ["HelpMountainLakeReliefMeters"] = "Мин. локальный рельеф для горного озера в метрах.",
            ["HelpLakeTectonicFaultThreshold"] = "Порог влияния тектонических разломов на образование озёр.",
            ["HelpLakeVolcanicInfluenceThreshold"] = "Порог вулканического влияния на образование озёр.",
            ["HelpPlainLakeKarstChance"] = "Вероятность карстовых озёр на равнинах.",
            ["HelpLakeDepthRandomnessMin"] = "Мин. множитель случайности глубины озёр.",
            ["HelpLakeDepthRandomnessMax"] = "Макс. множитель случайности глубины озёр.",
            ["HelpLargeLakeDepressionMinCellCount"] = "Мин. ячеек для депрессии, считающейся крупным озером.",
            ["HelpClimateLatitudeCurveExponent"] = "Контролирует падение температуры с широтой. Выше = круче к полюсам.",
            ["HelpClimateBaseSeasonalityCelsius"] = "Базовая сезонная вариация температуры, C.",
            ["HelpClimateLatitudeSeasonalityCelsius"] = "Доп. сезонность на высоких широтах, C.",
            ["HelpClimateContinentalSeasonalityCelsius"] = "Усиление сезонности внутри континентов, C.",
            ["HelpClimateContinentalSummerBoostCelsius"] = "Летнее усиление температур внутри континентов, C.",
            ["HelpClimateContinentalWinterPenaltyCelsius"] = "Зимний штраф температур внутри континентов, C.",
            ["HelpClimateContinentalityDistanceCells"] = "Дистанция от берега для континентальности, ячейки.",
            ["HelpClimateLargeLakeMinCellCount"] = "Мин. ячеек озера для влияния на местный климат.",
            ["HelpClimateOceanEvaporation"] = "Испарение с океана. Выше = больше влаги для осадков.",
            ["HelpClimateLakeEvaporation"] = "Испарение с озёр относительно океанов.",
            ["HelpClimateLandEvapotranspiration"] = "Эвапотранспирация суши. Выше = больше рециркуляции влаги.",
            ["HelpClimateMoistureRetention"] = "Удержание влаги атмосферой. Выше = более влажный климат.",
            ["HelpClimateBaseRainfallEfficiency"] = "Базовая эффективность превращения влаги в осадки.",
            ["HelpClimateDescentDrying"] = "Как сильно нисходящий воздух иссушает ландшафт.",
            ["HelpClimateContinentalDrying"] = "Потеря влаги при движении вглубь континента.",
            ["HelpClimateMonsoonRainStrength"] = "Сила усиления муссонных дождей.",
            ["HelpClimateDrySeasonStrength"] = "Сила сухого сезона в муссонных регионах.",
            ["HelpClimateMonsoonOceanDistanceCells"] = "Дальность муссонного влияния от океана, ячейки.",
            ["HelpClimateMonsoonCoastProbeCells"] = "Ячейки зондирования берега для муссонов."
        }
    };

    private string _language = "ru-RU";

    public event EventHandler? LanguageChanged;

    public IReadOnlyList<string> SupportedLanguages { get; } = ["ru-RU", "en-US"];

    public string Language
    {
        get => _language;
        set
        {
            var next = _resources.ContainsKey(value) ? value : "en-US";
            if (_language == next)
                return;

            _language = next;
            CultureInfo.CurrentUICulture = new CultureInfo(next);
            this.RaisePropertyChanged();
            this.RaisePropertyChanged("Item");
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public string this[string key]
    {
        get
        {
            if (_resources.TryGetValue(_language, out var language) && language.TryGetValue(key, out var localized))
                return localized;

            if (_resources["en-US"].TryGetValue(key, out var fallback))
                return fallback;

            return key;
        }
    }
}
