using System;
using System.Collections.Generic;
using System.Globalization;
using ReactiveUI;

namespace AvaloniaRegionizer.Services;

public sealed class LocalizationService : ReactiveObject
{
    private readonly Dictionary<string, Dictionary<string, string>> _resources = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en-US"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AppTitle"] = "MapRegionizer",
            ["SettingsTitle"] = "Generation settings",
            ["InputOutput"] = "Input and output",
            ["Mask"] = "Map mask",
            ["Output"] = "Output folder",
            ["Browse"] = "Browse",
            ["Choose"] = "Choose",
            ["Language"] = "Language",
            ["Theme"] = "Theme",
            ["Light"] = "Light",
            ["Dark"] = "Dark",
            ["System"] = "System",
            ["Preset"] = "Preset",
            ["FastPreview"] = "Fast preview",
            ["Balanced"] = "Balanced",
            ["Detailed"] = "Detailed",
            ["DiagnosticExport"] = "Diagnostic export",
            ["General"] = "General",
            ["Regions"] = "Regions",
            ["Boundaries"] = "Boundaries",
            ["Tectonics"] = "Tectonics",
            ["Elevation"] = "Elevation",
            ["Seed"] = "Seed",
            ["Randomize"] = "Randomize",
            ["Copy"] = "Copy",
            ["Projection"] = "Projection",
            ["PixelSize"] = "Pixel size",
            ["SimplifyTolerance"] = "Simplify tolerance",
            ["TargetArea"] = "Target region area",
            ["PointsMultiplier"] = "Points multiplier",
            ["MinAreaRatio"] = "Min area ratio",
            ["MaxAreaRatio"] = "Max area ratio",
            ["DistortionEnabled"] = "Distort boundaries",
            ["BoundaryDetail"] = "Boundary detail",
            ["MaxOffset"] = "Max offset",
            ["MinLineLengthToCurve"] = "Min line length to curve",
            ["PlateCount"] = "Plate count",
            ["HotspotCount"] = "Hotspot count",
            ["ContinentalSeedRatio"] = "Continental seed ratio",
            ["BoundaryNoise"] = "Boundary noise",
            ["BoundaryNoiseScale"] = "Boundary noise scale",
            ["LandWaterTransitionPenalty"] = "Land/water transition penalty",
            ["Activity"] = "Activity",
            ["EarthLikeFactor"] = "Earth-like factor",
            ["HistoryDepth"] = "History depth",
            ["MicroplateRatio"] = "Microplate ratio",
            ["MicroplateAreaRatio"] = "Microplate area ratio min/max",
            ["MinBoundarySegmentLength"] = "Min boundary segment length",
            ["ActiveMarginRatio"] = "Active margin ratio",
            ["ShelfWidthFactor"] = "Shelf width factor",
            ["RiftChance"] = "Rift chance",
            ["ValidateGeometry"] = "Validate geometry",
            ["ValidationCycles"] = "Validation cycles",
            ["MinPlateSize"] = "Min plate size",
            ["MinPlateSizeRatio"] = "Min plate size ratio",
            ["ReliefScale"] = "Relief scale",
            ["Mountaininess"] = "Mountaininess",
            ["Erosion"] = "Erosion",
            ["Roughness"] = "Roughness",
            ["SeaDepthScale"] = "Sea depth scale",
            ["PreserveCoastline"] = "Preserve mask coastline",
            ["VolcanismInfluence"] = "Volcanism influence",
            ["RiftInfluence"] = "Rift influence",
            ["MaxElevation"] = "Max elevation, m",
            ["MinOceanDepth"] = "Min ocean depth, m",
            ["MinLandElevation"] = "Min land elevation, m",
            ["MaxSeaElevation"] = "Max sea elevation, m",
            ["TectonicJson"] = "Tectonic JSON",
            ["ElevationJson"] = "Elevation JSON",
            ["LayerReady"] = "ready",
            ["Size"] = "Size",
            ["Landmasses"] = "Landmasses",
            ["WaterBodies"] = "Water bodies",
            ["Plates"] = "Plates",
            ["Features"] = "Features",
            ["RunFull"] = "Generate all",
            ["Export"] = "Export artifacts",
            ["Cancel"] = "Cancel",
            ["Preview"] = "Preview",
            ["Compare"] = "Compare previous",
            ["Layers"] = "Layers",
            ["Stages"] = "Stages",
            ["Statistics"] = "Statistics",
            ["History"] = "History",
            ["Artifacts"] = "Artifacts",
            ["Ready"] = "Ready",
            ["Generating"] = "Generating...",
            ["Completed"] = "Generation completed",
            ["Failed"] = "Generation failed",
            ["NotStarted"] = "Not started",
            ["Running"] = "Running",
            ["StageReady"] = "Ready",
            ["Dirty"] = "Dirty",
            ["StageFailed"] = "Failed",
            ["Unavailable"] = "Unavailable",
            ["RunUntil"] = "Run until",
            ["Regenerate"] = "Regenerate",
            ["FutureStages"] = "Future stages",
            ["Rivers"] = "Rivers",
            ["Climate"] = "Climate",
            ["Resources"] = "Resources",
            ["NoPreview"] = "No preview yet",
            ["NoHistory"] = "No runs yet",
            ["ValidationMask"] = "Choose an existing mask image.",
            ["ValidationOutput"] = "Choose an output folder.",
            ["ValidationOptions"] = "Fix invalid generation settings.",
            ["StatusChooseMask"] = "Choose a mask to begin.",
            ["StatusSessionReset"] = "Session will be recreated on the next run.",
            ["StatusDirty"] = "Settings changed. Affected stages are dirty.",
            ["StatusExported"] = "Artifacts exported.",
            ["LayerOverview"] = "Overview",
            ["LayerRegions"] = "Regions",
            ["LayerTectonicPlates"] = "Tectonic plates",
            ["LayerCrust"] = "Crust",
            ["LayerFeatures"] = "Tectonic features",
            ["LayerElevation"] = "Elevation",
            ["LayerElevationBase"] = "Elevation base",
            ["LayerElevationTectonic"] = "Tectonic elevation",
            ["LayerElevationRoughness"] = "Roughness",
            ["LayerElevationErosion"] = "Erosion mask",
            ["LayerElevationZones"] = "Terrain zones",
            ["LayerElevationMountain"] = "Mountain influence",
            ["LayerElevationBasin"] = "Basin influence",
            ["LegendOverview"] = "Land, water, and generated region borders.",
            ["LegendTectonics"] = "Plate ids, plate boundaries, and tectonic diagnostics.",
            ["LegendElevation"] = "Hypsometric terrain and bathymetry.",
            ["LegendNotAvailable"] = "Run the required stage to render this layer."
            ,["StageLandmasses"] = "Extract landmasses",
            ["StageWaterBodies"] = "Extract water bodies",
            ["StageTectonicHistory"] = "Tectonic history",
            ["StageCrustFields"] = "Crust fields",
            ["StagePlateDomains"] = "Plate domains",
            ["StageTectonicBoundaries"] = "Tectonic boundaries",
            ["StageTectonicFeatures"] = "Tectonic features",
            ["StageElevation"] = "Elevation",
            ["StageTectonicPlates"] = "Assemble tectonic map",
            ["StageRawRegions"] = "Raw regions",
            ["StageRegions"] = "Final regions"
        },
        ["ru-RU"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AppTitle"] = "MapRegionizer",
            ["SettingsTitle"] = "Настройки генерации",
            ["InputOutput"] = "Ввод и вывод",
            ["Mask"] = "Маска карты",
            ["Output"] = "Папка вывода",
            ["Browse"] = "Обзор",
            ["Choose"] = "Выбрать",
            ["Language"] = "Язык",
            ["Theme"] = "Тема",
            ["Light"] = "Светлая",
            ["Dark"] = "Темная",
            ["System"] = "Системная",
            ["Preset"] = "Пресет",
            ["FastPreview"] = "Быстрый просмотр",
            ["Balanced"] = "Сбалансированный",
            ["Detailed"] = "Детальный",
            ["DiagnosticExport"] = "Диагностический экспорт",
            ["General"] = "Общие",
            ["Regions"] = "Регионы",
            ["Boundaries"] = "Границы",
            ["Tectonics"] = "Тектоника",
            ["Elevation"] = "Рельеф",
            ["Seed"] = "Seed",
            ["Randomize"] = "Случайный",
            ["Copy"] = "Копировать",
            ["Projection"] = "Проекция",
            ["PixelSize"] = "Масштаб пикселя",
            ["SimplifyTolerance"] = "Упрощение маски",
            ["TargetArea"] = "Целевая площадь региона",
            ["PointsMultiplier"] = "Множитель точек",
            ["MinAreaRatio"] = "Мин. отношение площади",
            ["MaxAreaRatio"] = "Макс. отношение площади",
            ["DistortionEnabled"] = "Искажать границы",
            ["BoundaryDetail"] = "Детализация границ",
            ["MaxOffset"] = "Макс. отступ",
            ["MinLineLengthToCurve"] = "Мин. длина для изгиба",
            ["PlateCount"] = "Количество плит",
            ["HotspotCount"] = "Количество хотспотов",
            ["ContinentalSeedRatio"] = "Доля континентальных сидов",
            ["BoundaryNoise"] = "Шум границ",
            ["BoundaryNoiseScale"] = "Масштаб шума границ",
            ["LandWaterTransitionPenalty"] = "Штраф перехода суша/вода",
            ["Activity"] = "Активность",
            ["EarthLikeFactor"] = "Землеподобность",
            ["HistoryDepth"] = "Глубина истории",
            ["MicroplateRatio"] = "Доля микроплит",
            ["MicroplateAreaRatio"] = "Мин/макс. доля площади микроплит",
            ["MinBoundarySegmentLength"] = "Мин. длина сегмента границы",
            ["ActiveMarginRatio"] = "Доля активных окраин",
            ["ShelfWidthFactor"] = "Множитель ширины шельфа",
            ["RiftChance"] = "Вероятность рифта",
            ["ValidateGeometry"] = "Проверять геометрию",
            ["ValidationCycles"] = "Циклы проверки",
            ["MinPlateSize"] = "Мин. размер плиты",
            ["MinPlateSizeRatio"] = "Мин. доля размера плиты",
            ["ReliefScale"] = "Масштаб рельефа",
            ["Mountaininess"] = "Гористость",
            ["Erosion"] = "Эрозия",
            ["Roughness"] = "Шероховатость",
            ["SeaDepthScale"] = "Глубина морей",
            ["PreserveCoastline"] = "Сохранять береговую линию маски",
            ["VolcanismInfluence"] = "Влияние вулканизма",
            ["RiftInfluence"] = "Влияние рифтов",
            ["MaxElevation"] = "Макс. высота, м",
            ["MinOceanDepth"] = "Мин. глубина океана, м",
            ["MinLandElevation"] = "Мин. высота суши, м",
            ["MaxSeaElevation"] = "Макс. высота моря, м",
            ["TectonicJson"] = "JSON тектоники",
            ["ElevationJson"] = "JSON рельефа",
            ["LayerReady"] = "готово",
            ["Size"] = "Размер",
            ["Landmasses"] = "Массивы суши",
            ["WaterBodies"] = "Водоемы",
            ["Plates"] = "Плиты",
            ["Features"] = "Признаки",
            ["RunFull"] = "Сгенерировать все",
            ["Export"] = "Экспортировать",
            ["Cancel"] = "Отмена",
            ["Preview"] = "Просмотр",
            ["Compare"] = "Сравнить с прошлым",
            ["Layers"] = "Слои",
            ["Stages"] = "Стадии",
            ["Statistics"] = "Статистика",
            ["History"] = "История",
            ["Artifacts"] = "Артефакты",
            ["Ready"] = "Готово",
            ["Generating"] = "Генерация...",
            ["Completed"] = "Генерация завершена",
            ["Failed"] = "Ошибка генерации",
            ["NotStarted"] = "Не запускалась",
            ["Running"] = "Выполняется",
            ["StageReady"] = "Готова",
            ["Dirty"] = "Устарела",
            ["StageFailed"] = "Ошибка",
            ["Unavailable"] = "Недоступно",
            ["RunUntil"] = "До стадии",
            ["Regenerate"] = "Перегенерировать",
            ["FutureStages"] = "Будущие стадии",
            ["Rivers"] = "Реки",
            ["Climate"] = "Климат",
            ["Resources"] = "Ресурсы",
            ["NoPreview"] = "Превью пока нет",
            ["NoHistory"] = "Запусков пока нет",
            ["ValidationMask"] = "Выберите существующий файл маски.",
            ["ValidationOutput"] = "Выберите папку вывода.",
            ["ValidationOptions"] = "Исправьте некорректные настройки генерации.",
            ["StatusChooseMask"] = "Выберите маску, чтобы начать.",
            ["StatusSessionReset"] = "Сессия будет пересоздана при следующем запуске.",
            ["StatusDirty"] = "Настройки изменены. Зависимые стадии устарели.",
            ["StatusExported"] = "Артефакты экспортированы.",
            ["LayerOverview"] = "Обзор",
            ["LayerRegions"] = "Регионы",
            ["LayerTectonicPlates"] = "Тектонические плиты",
            ["LayerCrust"] = "Кора",
            ["LayerFeatures"] = "Тектонические features",
            ["LayerElevation"] = "Рельеф",
            ["LayerElevationBase"] = "База рельефа",
            ["LayerElevationTectonic"] = "Тектонический вклад",
            ["LayerElevationRoughness"] = "Шероховатость",
            ["LayerElevationErosion"] = "Маска эрозии",
            ["LayerElevationZones"] = "Зоны рельефа",
            ["LayerElevationMountain"] = "Влияние гор",
            ["LayerElevationBasin"] = "Влияние бассейнов",
            ["LegendOverview"] = "Суша, вода и границы сгенерированных регионов.",
            ["LegendTectonics"] = "Идентификаторы плит, границы плит и тектоническая диагностика.",
            ["LegendElevation"] = "Гипсометрический рельеф и батиметрия.",
            ["LegendNotAvailable"] = "Запустите нужную стадию, чтобы отрисовать этот слой."
            ,["StageLandmasses"] = "Извлечение суши",
            ["StageWaterBodies"] = "Извлечение водоемов",
            ["StageTectonicHistory"] = "Тектоническая история",
            ["StageCrustFields"] = "Поля коры",
            ["StagePlateDomains"] = "Домены плит",
            ["StageTectonicBoundaries"] = "Границы плит",
            ["StageTectonicFeatures"] = "Тектонические признаки",
            ["StageElevation"] = "Рельеф",
            ["StageTectonicPlates"] = "Сборка карты плит",
            ["StageRawRegions"] = "Черновые регионы",
            ["StageRegions"] = "Финальные регионы"
        }
    };

    private string _language = "ru-RU";

    public event EventHandler? LanguageChanged;

    public IReadOnlyList<string> SupportedLanguages { get; } = ["ru-RU", "en-US"];

    public string Language
    {
        get => _language;
        set
        {
            var next = _resources.ContainsKey(value) ? value : "en-US";
            if (_language == next)
                return;

            _language = next;
            CultureInfo.CurrentUICulture = new CultureInfo(next);
            this.RaisePropertyChanged();
            this.RaisePropertyChanged("Item");
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public string this[string key]
    {
        get
        {
            if (_resources.TryGetValue(_language, out var language) && language.TryGetValue(key, out var localized))
                return localized;

            if (_resources["en-US"].TryGetValue(key, out var fallback))
                return fallback;

            return key;
        }
    }
}
